In [3]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\sharanya\.conda\.jupyter\lib\site-packages (9.7.0)

In [4]:
import mysql.connector
import pandas as pd
customer_behaviour= mysql.connector.connect(host="localhost",user="root",password="S9177278530@123",database="customer")
query="select * from customer_shopping_behavior"
df=pd.read_sql(query,customer_behaviour)
df

C:\Users\Sharanya\AppData\Local\Temp\ipykernel_1356\891344806.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query,customer_behaviour)

,ï»¿Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3858,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3859,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3860,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3861,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3862,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [6]:
df.head(5)
df.tail(5)
df.info()
df.describe()
df.isna()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3863 entries, 0 to 3862
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ï»¿Customer ID          3863 non-null   int64
 1   Age                     3863 non-null   int64
 2   Gender                  3863 non-null   object
 3   Item Purchased          3863 non-null   object
 4   Category                3863 non-null   object
 5   Purchase Amount (USD)   3863 non-null   int64
 6   Location                3863 non-null   object
 7   Size                    3863 non-null   object
 8   Color                   3863 non-null   object
 9   Season                  3863 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3863 non-null   object
 12  Shipping Type           3863 non-null   object
 13  Discount Applied        3863 non-null   object
 14  Promo Code Used         3863 non-null   object
 15  Previous Purchases      3863 non-null   int64
 16  Payment Method          3863 non-null   object
 17  Frequency of Purchases  3863 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 543.4+ KB

ï»¿Customer ID            0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
df.shape

(3863, 18)

In [10]:
#snakecasing
df.columns

Index(['ï»¿Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [11]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(" ","_")
df.columns

Index(['ï»¿customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [13]:
#remaning the columns
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df=df.rename(columns={'ï»¿Customer ID':'customer_id'})
df.columns

Index(['ï»¿customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [17]:
df=df.rename(columns={'ï»¿customer_id':'customer_id'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [18]:
#converting text to values & values to text
labels=['young','adult','middle_aged','senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)
df[['age','age_group']].head(5)

   age    age_group
0   55  middle_aged
1   19        young
2   50  middle_aged
3   21        young
4   45  middle_aged

In [19]:
frequncy_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Annually':365,
    'Bi-weekly':14,
    'Every3months':90
}
df['purchase_frequncy_days']=df['frequency_of_purchases'].map(frequncy_mapping)
df[['frequency_of_purchases','purchase_frequncy_days']].head(10)

  frequency_of_purchases  purchase_frequncy_days
0            Fortnightly                    14.0
1            Fortnightly                    14.0
2                 Weekly                     7.0
3                 Weekly                     7.0
4               Annually                   365.0
5                 Weekly                     7.0
6              Quarterly                    90.0
7                 Weekly                     7.0
8               Annually                   365.0
9              Quarterly                    90.0

In [21]:
df.to_excel("customer.xlsx",index='false')